Repository vercel/nft, pull requests merged in 2019-08, with the labels that each got.

#37 Add special case for `bull`
  azure-prepare.js
  package.json
  src/utils/special-cases.js
  test/integration/bull.js
  yarn.lock
Labels: automerge

#38 Add automerge config
  .kodiak.toml
Labels: automerge

#41 Fix `uglify-js` special case
  package.json
  src/utils/special-cases.js
  test/integration/uglify.js
  yarn.lock
Labels: automerge

#42 Update readme.md
  readme.md
Labels: automerge, documentation

#40 Trace `.tsx` input files
  src/analyze.js
  src/node-file-trace.js
  test/unit.test.js
  test/unit/tsx-input/dep.tsx
  test/unit/tsx-input/input.tsx
  test/unit/tsx-input/output.js
Labels: automerge

#46 Fix `phantomjs-prebuilt` binary
  package.json
  src/utils/special-cases.js
  test/unit/phantomjs-prebuilt/input.js
  test/unit/phantomjs-prebuilt/output.js
  yarn.lock
Labels: automerge

#49 Add GitHub Actions CI
  .circleci/config.yml
  .github/workflows/ci.yml
  azure-pipelines.yml
  package.json
Labels: automerge, tests

#51 Support webpack-style Node requires
  src/analyze.js
  src/utils/static-eval.js
  test/unit/webpack-node/input.js
  test/unit/webpack-node/level1/a.b.js
  test/unit/webpack-node/level1/c.d.js
  test/unit/webpack-node/level1/level2/level3/page.js
  test/unit/webpack-node/output.js
Labels: automerge, priority

#50 Rename azure-prepare.js to windows-prepare.js
  .github/workflows/ci.yml
  windows-prepare.js
Labels: automerge

#52 Prevent CI for tags
  .github/workflows/ci.yml
Labels: automerge, tests

#53 Fix `argon2` with special case
  package.json
  src/utils/special-cases.js
  test/integration/argon2.js
  windows-prepare.js
  yarn.lock
Labels: automerge

#57 Update typescript types
  node-file-trace.d.ts
Labels: automerge
